# Generated by Django 4.0.6 on 2024-02-17 06:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Allops', '0008_alter_mails_fields_alter_opportunity_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Externship', 'Externship'), ('Student Program', 'Student Program'), ('Scholarship', 'Scholarship'), ('Apprenticeship', 'Apprenticeship'), ('Training', 'Training'), ('Language', 'Language'), ('Social Good', 'Social Good'), ('Open Ended', 'Open Ended'), ('Meet up', 'Meet up'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Machine Learning/AI', 'Machine Learning/AI'), ('Blockchain', 'Blockchain'), ('Design', 'Design'), ('Web', 'Web'), ('AR/VR', 'AR/VR'), ('Gaming', 'Gaming'), ('IoT', 'IoT'), ('DevOps', 'DevOps'), ('Cloud', 'Cloud'), ('Cybersecurity', 'Cybersecurity'), ('Mobile', 'Mobile'), ('Data', 'Data'), ('Music/Art', 'Music/Art')], max_length=25),
        ),
    ]
